### ISSUE TITLE
SMS-INCOMING FUNCTION is not always responding timely or at all

### ISSUE THREAD

**Issue by brainomite** [MutualAidNYC/mutual-aid-call-center#68]
We've been getting these 2 errors a bunch of times, we need to trace
1)
```
2020-08-07 19:46:43.584 340 <158>1 2020-08-07T19:46:43.325978+00:00 heroku router - - at=error code=H12 desc="Request timeout" method=POST path="/api/sms-incoming" host=phone.mutualaid.nyc request_id=c9416141-a86c-4bd7-9ea8-dd3ec70229fb fwd="54.91.234.88" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
```
2)
```
2020-08-07T18:36:54.590094+00:00 heroku router - - at=error code=H12 desc="Request timeout" method=POST path="/api/sms-incoming" host=phone.mutualaid.nyc request_id=9f9e616c-6ce8-4fc6-9900-90b1ba682bb6 fwd="34.207.216.154" dyno=web.1 connect=0ms service=30006ms status=503 bytes=0 protocol=https

**Comment by brainomite** [comment]
happened again today
```
28 Aug 2020 16:47:40.994255 <190>1 2020-08-28T20:47:40.374385+00:00 app web.1 - - (node:4) UnhandledPromiseRejectionWarning: Error: Worker WKd8e7d08e3232602c1caa1208000a2435 cannot have its activity updated while it has 1 pending reservations.
    at success (/app/node_modules/twilio/lib/base/Version.js:88:15)
    at Promise_then_fulfilled (/app/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/app/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/app/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/app/node_modules/q/q.js:1369:30)
    at RawTask.call (/app/node_modules/asap/asap.js:40:19)
    at flush (/app/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)Exception
28 Aug 2020 16:47:40.994518 <190>1 2020-08-28T20:47:40.374475+00:00 app web.1 - - (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
28 Aug 2020 16:47:50.046306 <158>1 2020-08-28T20:47:49.881429+00:00 heroku router - - at=info method=POST path="/api/agent-gather" host=phone.mutualaid.nyc request_id=7884fcdc-2abe-401e-aa3b-336c0ed35c93 fwd="3.94.10.165" dyno=web.1 connect=10ms service=56ms status=200 bytes=268 protocol=https
28 Aug 2020 16:47:50.118239 <190>1 2020-08-28T20:47:49.827501+00:00 app web.1 - - {"level":30,"time":1598647669827,"pid":4,"hostname":"3ce04270-e73a-4366-8ef8-b312aa323546","msg":"Agent Gather Debug: Entered function, digit: "}
28 Aug 2020 16:47:50.237239 <190>1 2020-08-28T20:47:49.875433+00:00 app web.1 - - {"level":30,"time":1598647669875,"pid":4,"hostname":"3ce04270-e73a-4366-8ef8-b312aa323546","msg":"Agent Gather Debug: pending reservation found"}
28 Aug 2020 16:47:50.237237 <190>1 2020-08-28T20:47:49.881173+00:00 app web.1 - - {"level":30,"time":1598647669875,"pid":4,"hostname":"3ce04270-e73a-4366-8ef8-b312aa323546","msg":"Agent Gather Debug: before reject no digits"}
28 Aug 2020 16:47:50.237237 <190>1 2020-08-28T20:47:49.881174+00:00 app web.1 - - {"level":30,"time":1598647669876,"pid":4,"hostname":"3ce04270-e73a-4366-8ef8-b312aa323546","msg":"Agent Gather Debug: Post Reject Reservation"}
28 Aug 2020 16:47:50.237229 <190>1 2020-08-28T20:47:49.881175+00:00 app web.1 - - {"level":30,"time":1598647669876,"pid":4,"hostname":"3ce04270-e73a-4366-8ef8-b312aa323546","msg":"Agent Gather Debug: End of function"}
28 Aug 2020 16:47:53.097311 <158>1 2020-08-28T20:47:52.504245+00:00 heroku router - - at=info method=POST path="/api/workspace-event" host=phone.mutualaid.nyc request_id=cfc150c5-a619-4ead-9cfa-bb60a1b0bddc fwd="54.209.162.81" dyno=web.1 connect=21ms service=18ms status=200 bytes=201 protocol=https
28 Aug 2020 16:47:55.215310 <158>1 2020-08-28T20:47:52.708825+00:00 heroku router - - at=info method=POST path="/api/workspace-event" host=phone.mutualaid.nyc request_id=15c40162-00cf-4a0a-8e53-4c07ea2b1f8b fwd="54.164.37.41" dyno=web.1 connect=22ms service=10ms status=200 bytes=201 protocol=https
28 Aug 2020 16:47:55.296336 <158>1 2020-08-28T20:47:52.757970+00:00 heroku router - - at=info method=GET path="/assets/no_volunteers_available_in_english.mp3" host=phone.mutualaid.nyc request_id=7c72e053-4a43-4c67-886d-9a8c0df3d393 fwd="3.90.109.241" dyno=web.1 connect=1ms service=12ms status=200 bytes=69875 protocol=https
28 Aug 2020 16:47:55.684341 <158>1 2020-08-28T20:47:55.593238+00:00 heroku router - - at=error code=H12 desc="Request timeout" method=POST path="/api/sms-incoming" host=phone.mutualaid.nyc request_id=60af5fc5-009d-4303-b9e5-73799fd39e04 fwd="54.175.31.247" dyno=web.1 connect=0ms service=30004ms status=503 bytes=0 protocol=https
```

**Comment by brainomite** [comment]
Bug, at least this time, appears to be how to handle when the sole volunteer wants to clock out while a call is coming in.

this appears to be a solution, reject with a keypress and clock out simultaneously 
https://www.twilio.com/docs/taskrouter/api/reservations#reject
